CREATE TABLE `admin_action_audit_logs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `actorUserId` int,
  `actorRole` varchar(32),
  `actorAdminLevel` varchar(32),
  `actionType` varchar(96) NOT NULL,
  `actionLabel` varchar(255) NOT NULL,
  `actionStatus` enum('success','failed','blocked') NOT NULL DEFAULT 'success',
  `resourceType` varchar(64),
  `resourceId` varchar(128),
  `resourceLabel` varchar(255),
  `targetUserId` int,
  `relatedOrderId` int,
  `snapshotId` int,
  `ipAddress` varchar(96),
  `userAgent` varchar(255),
  `metadata` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `admin_action_audit_logs_id` PRIMARY KEY(`id`),
  CONSTRAINT `admin_action_audit_logs_actorUserId_users_id_fk` FOREIGN KEY (`actorUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_action_audit_logs_targetUserId_users_id_fk` FOREIGN KEY (`targetUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_action_audit_logs_relatedOrderId_orders_id_fk` FOREIGN KEY (`relatedOrderId`) REFERENCES `orders`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_action_audit_logs_snapshotId_system_config_snapshots_id_fk` FOREIGN KEY (`snapshotId`) REFERENCES `system_config_snapshots`(`id`) ON DELETE no action ON UPDATE no action
);
