CREATE TABLE `admin_risk_incidents` (
  `id` int AUTO_INCREMENT NOT NULL,
  `auditLogId` int NOT NULL,
  `severity` enum('warn','critical') NOT NULL DEFAULT 'warn',
  `riskScore` int NOT NULL DEFAULT 0,
  `status` enum('open','acknowledged','resolved') NOT NULL DEFAULT 'open',
  `escalationLevel` int NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL,
  `summary` text,
  `payload` text,
  `firstSeenAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastSeenAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastEscalatedAt` timestamp NULL,
  `acknowledgedAt` timestamp NULL,
  `acknowledgedByUserId` int NULL,
  `resolvedAt` timestamp NULL,
  `resolvedByUserId` int NULL,
  `handlingNote` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `admin_risk_incidents_id` PRIMARY KEY(`id`),
  CONSTRAINT `admin_risk_incidents_auditLogId_admin_action_audit_logs_id_fk` FOREIGN KEY (`auditLogId`) REFERENCES `admin_action_audit_logs`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_risk_incidents_acknowledgedByUserId_users_id_fk` FOREIGN KEY (`acknowledgedByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_risk_incidents_resolvedByUserId_users_id_fk` FOREIGN KEY (`resolvedByUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `admin_risk_incidents_auditLogId_unique` UNIQUE(`auditLogId`)
);
